# Generated by Django 2.1 on 2019-02-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('metrics', models.CharField(max_length=20)),
                ('value', models.FloatField(default=0)),
                ('date', models.DateField(max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('location', 'metrics', 'date')},
        ),
    ]
